package com.mx.cji.crm.models.entity;
// Generated 19/06/2019 04:57:48 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblActaconstitutiva generated by hbm2java
 */
@Entity
@Table(name = "tbl_actaconstitutiva", catalog = "cji")
public class Acta implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private int idImgActaconstitutiva;
	private String apoderado;
	private String socio1;
	private String administrador;
	private String representante;

	public Acta() {
	}

	public Acta(int idImgActaconstitutiva, String apoderado, String socio1, String administrador,
			String representante) {
		this.idImgActaconstitutiva = idImgActaconstitutiva;
		this.apoderado = apoderado;
		this.socio1 = socio1;
		this.administrador = administrador;
		this.representante = representante;
	}

	@Id

	@Column(name = "id_imgActaconstitutiva", unique = true, nullable = false)
	public int getIdImgActaconstitutiva() {
		return this.idImgActaconstitutiva;
	}

	public void setIdImgActaconstitutiva(int idImgActaconstitutiva) {
		this.idImgActaconstitutiva = idImgActaconstitutiva;
	}

	@Column(name = "apoderado", nullable = false, length = 50)
	public String getApoderado() {
		return this.apoderado;
	}

	public void setApoderado(String apoderado) {
		this.apoderado = apoderado;
	}

	@Column(name = "socio1", nullable = false, length = 50)
	public String getSocio1() {
		return this.socio1;
	}

	public void setSocio1(String socio1) {
		this.socio1 = socio1;
	}

	@Column(name = "administrador", nullable = false, length = 50)
	public String getAdministrador() {
		return this.administrador;
	}

	public void setAdministrador(String administrador) {
		this.administrador = administrador;
	}

	@Column(name = "representante", nullable = false, length = 50)
	public String getRepresentante() {
		return this.representante;
	}

	public void setRepresentante(String representante) {
		this.representante = representante;
	}

}
