package com.mx.cji.crm.models.entity;
// Generated 19/06/2019 04:57:48 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatContableId generated by hbm2java
 */
@Embeddable
public class CatContableId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer idContable;
	private String nombre;

	public CatContableId() {
	}

	public CatContableId(Integer idContable, String nombre) {
		this.idContable = idContable;
		this.nombre = nombre;
	}

	@Column(name = "id_contable")
	public Integer getIdContable() {
		return this.idContable;
	}

	public void setIdContable(Integer idContable) {
		this.idContable = idContable;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatContableId))
			return false;
		CatContableId castOther = (CatContableId) other;

		return ((this.getIdContable() == castOther.getIdContable()) || (this.getIdContable() != null
				&& castOther.getIdContable() != null && this.getIdContable().equals(castOther.getIdContable())))
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdContable() == null ? 0 : this.getIdContable().hashCode());
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		return result;
	}

}
