package com.mx.cji.crm.models.entity;
// Generated 19/06/2019 04:57:48 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CatFiscal generated by hbm2java
 */
@Entity
@Table(name = "cat_fiscal", catalog = "cji")
public class CatFiscal implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private CatFiscalId id;

	public CatFiscal() {
	}

	public CatFiscal(CatFiscalId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idFiscal", column = @Column(name = "id_fiscal")),
			@AttributeOverride(name = "nombre", column = @Column(name = "nombre", length = 100)) })
	public CatFiscalId getId() {
		return this.id;
	}

	public void setId(CatFiscalId id) {
		this.id = id;
	}

}
