package com.mx.cji.crm.models.entity;
// Generated 19/06/2019 04:57:48 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatFiscalId generated by hbm2java
 */
@Embeddable
public class CatFiscalId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer idFiscal;
	private String nombre;

	public CatFiscalId() {
	}

	public CatFiscalId(Integer idFiscal, String nombre) {
		this.idFiscal = idFiscal;
		this.nombre = nombre;
	}

	@Column(name = "id_fiscal")
	public Integer getIdFiscal() {
		return this.idFiscal;
	}

	public void setIdFiscal(Integer idFiscal) {
		this.idFiscal = idFiscal;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatFiscalId))
			return false;
		CatFiscalId castOther = (CatFiscalId) other;

		return ((this.getIdFiscal() == castOther.getIdFiscal()) || (this.getIdFiscal() != null
				&& castOther.getIdFiscal() != null && this.getIdFiscal().equals(castOther.getIdFiscal())))
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdFiscal() == null ? 0 : this.getIdFiscal().hashCode());
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		return result;
	}

}
