package com.mx.cji.crm.models.entity;
// Generated 19/06/2019 04:57:48 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatJuridicoId generated by hbm2java
 */
@Embeddable
public class CatJuridicoId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer idJuridico;
	private String nombre;

	public CatJuridicoId() {
	}

	public CatJuridicoId(Integer idJuridico, String nombre) {
		this.idJuridico = idJuridico;
		this.nombre = nombre;
	}

	@Column(name = "id_juridico")
	public Integer getIdJuridico() {
		return this.idJuridico;
	}

	public void setIdJuridico(Integer idJuridico) {
		this.idJuridico = idJuridico;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatJuridicoId))
			return false;
		CatJuridicoId castOther = (CatJuridicoId) other;

		return ((this.getIdJuridico() == castOther.getIdJuridico()) || (this.getIdJuridico() != null
				&& castOther.getIdJuridico() != null && this.getIdJuridico().equals(castOther.getIdJuridico())))
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdJuridico() == null ? 0 : this.getIdJuridico().hashCode());
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		return result;
	}

}
