package com.mx.cji.crm.models.entity;
// Generated 19/06/2019 04:57:48 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatCliente generated by hbm2java
 */
@Entity
@Table(name = "cat_cliente", catalog = "cji")
public class Cliente implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer idCliente;
	private String username;
	private String password;
	private String enabled;
	private Set<Empresa> tblEmpresas = new HashSet<Empresa>(0);

	public Cliente() {
	}

	public Cliente(String username, String password, String enabled, Set<Empresa> tblEmpresas) {
		this.username = username;
		this.password = password;
		this.enabled = enabled;
		this.tblEmpresas = tblEmpresas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_cliente", unique = true, nullable = false)
	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	@Column(name = "username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "enabled", length = 50)
	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catCliente")
	public Set<Empresa> getTblEmpresas() {
		return this.tblEmpresas;
	}

	public void setTblEmpresas(Set<Empresa> tblEmpresas) {
		this.tblEmpresas = tblEmpresas;
	}

}
