package com.mx.cji.crm.models.entity;
// Generated 19/06/2019 04:57:48 PM by Hibernate Tools 4.3.5.Final

 
import java.util.Date;
 

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.web.multipart.MultipartFile;

/**
 * TblEmpresa generated by hbm2java
 */
@Entity
@Table(name = "tbl_empresas")
public class Empresa implements java.io.Serializable {
	@Id	
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="id")
	private int id;
	
	private String code;	
	
	@NotEmpty
	private String nombre;
	@NotEmpty
	@Size(min=1 , max=12)
	private String rfc;
	@NotEmpty
	private String estatus;
	@NotEmpty
	private String giro;
	 
	@Column(name="create_At") 
	private Date creaAte;
	
	@PrePersist
	 public void prePersist() {
			creaAte= new  Date();
	 }
	
	@NotNull
	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="grupo_id")
	private Grupo grupo; 
	
	@NotNull
	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="patio_id")
	private Patio patio; 
	
	@NotNull
	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="legal_id")
	private Representante legalId; 
			
	
	@Transient
	private MultipartFile file;
			
	public MultipartFile getFile() {
		return file;
	}

	public void setFile(MultipartFile file) {
		this.file = file;
	}

	
	@Column(name="fiel")
	private String existeFile;
	
	 
	
	
	
	
	
   public Empresa() {
		
		//this.code = "RPT" + UUID.randomUUID().toString().substring(26).toUpperCase();
	}
	
	
	 
    @Column(name="user_id")
	private int userId;		
	
	
	
	public int getId() {
		return id;
	}


	public void setId(int id) {
		this.id = id;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}
	


	public String getNombre() {
		return nombre;
	}


	public void setNombre(String nombre) {
		this.nombre = nombre;
	}


	public String getRfc() {
		return rfc;
	}


	public void setRfc(String rfc) {
		this.rfc = rfc;
	}


	public String getEstatus() {
		return estatus;
	}



	public void setEstatus(String estatus) {
		this.estatus = estatus;
	}



	public String getGiro() {
		return giro;
	}


	public void setGiro(String giro) {
		this.giro = giro;
	}


	public Date getCreaAte() {
		return creaAte;
	}

	public void setCreaAte(Date creaAte) {
		this.creaAte = creaAte;
	}


	public Grupo getGrupo() {
		return grupo;
	}


	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}


	public Patio getPatio() {
		return patio;
	}


	public void setPatio(Patio patio) {
		this.patio = patio;
	}


	public Representante getlegalId() {
		return legalId;
	}


	public void setlegalId(Representante legalId) {
		this.legalId = legalId;
	}

	public int getUserId() {
		return userId;
	}



	public void setUserId(int userId) {
		this.userId = userId;
	}

	private static final long serialVersionUID = 1L;

	
	 
	@Transient
	public String getExisteFile() {
		return existeFile;
	}

	public void setExisteFile(String existeFile) {
		this.existeFile = existeFile;
	}

	
	
	@Override
	public String toString() {
		return "Empresa [id=" + id + ",code="+code+", nombre=" + nombre + ", rfc=" + rfc + ", estatus=" + estatus + ", giro=" + giro
				+", creaAte=" + creaAte + ", grupo=" + grupo + ", patio=" + patio + ", legalId="
				+ legalId + ", userId=" + userId + ",existeFile="+existeFile+"]";
	}
	
	
	
	
	
}
