package com.mx.cji.crm.models.entity;
// Generated 19/06/2019 04:57:48 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblEstadocuenta generated by hbm2java
 */
@Entity
@Table(name = "tbl_estadocuenta", catalog = "cji")
public class Estadocuenta implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer idImgEstadocuenta;
	private String banco;
	private String periodo;
	private String domicilio;

	public Estadocuenta() {
	}

	public Estadocuenta(String banco, String periodo, String domicilio) {
		this.banco = banco;
		this.periodo = periodo;
		this.domicilio = domicilio;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_imgEstadocuenta", unique = true, nullable = false)
	public Integer getIdImgEstadocuenta() {
		return this.idImgEstadocuenta;
	}

	public void setIdImgEstadocuenta(Integer idImgEstadocuenta) {
		this.idImgEstadocuenta = idImgEstadocuenta;
	}

	@Column(name = "banco", length = 50)
	public String getBanco() {
		return this.banco;
	}

	public void setBanco(String banco) {
		this.banco = banco;
	}

	@Column(name = "periodo", length = 50)
	public String getPeriodo() {
		return this.periodo;
	}

	public void setPeriodo(String periodo) {
		this.periodo = periodo;
	}

	@Column(name = "domicilio", length = 50)
	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

}
