package com.mx.cji.crm.models.entity;
// Generated 19/06/2019 04:57:48 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CatPatio generated by hbm2java
 */
@Entity
@Table(name ="cat_patios")
public class Patio implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="id")
	private int id;
	
	private String calle;
	private String colonia;
	private String delegacion;
	private String ciudad;
	private String cp;
	private Integer user_Id;
	
	@Column(name="create_At")
	@Temporal(TemporalType.TIMESTAMP)
	private Date createAt;
	
	

	@PrePersist
	public void prePersist() {
	 createAt = new Date();		
	}
	 
	public Patio() {
	}

	public Patio(Integer id,String calle, String colonia, String delegacion, String ciudad, String cp,Integer user_Id) {
		this.id=id;
		this.calle = calle;
		this.colonia = colonia;
		this.delegacion = delegacion;
		this.ciudad = ciudad;
		this.cp = cp;
		this.user_Id=user_Id;
		 
	}

	 

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "calle", length = 100)
	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	@Column(name = "colonia", length = 100)
	public String getColonia() {
		return this.colonia;
	}

	public void setColonia(String colonia) {
		this.colonia = colonia;
	}

	@Column(name = "delegacion", length = 100)
	public String getDelegacion() {
		return this.delegacion;
	}

	public void setDelegacion(String delegacion) {
		this.delegacion = delegacion;
	}

	@Column(name = "ciudad", length = 100)
	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "cp", length = 5)
	public String getCp() {
		return this.cp;
	}

	public void setCp(String cp) {
		this.cp = cp;
	}

	public Integer getUser_Id() {
		return user_Id;
	}

	public void setUser_Id(Integer user_Id) {
		this.user_Id = user_Id;
	}
	
	
	 @Override
	    public String toString() {
	        final StringBuilder builder = new StringBuilder();
	        builder.append("Patio [id=").append(id).append(", calle=").append(calle).append("]");
	        return builder.toString();
	    }

	
	private static final long serialVersionUID = 1L;

}
