package com.mx.cji.crm.models.entity;
// Generated 19/06/2019 04:57:48 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;


import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.stereotype.Component;
import org.springframework.web.multipart.MultipartFile;

/**
 * TblRepresentante generated by hbm2java
 */

@Component
@Entity
@Table(name = "tbl_representantes")

public class Representante implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int id;
   
	private int user_id; 
	@NotEmpty
	private String nombre;
	
    private String rfc;
    private String curp;
     
    private String doctoPdf;
    
    @Column(name="create_At")
    @Temporal(TemporalType.TIMESTAMP)
	private Date createAt;
	
	@PrePersist
    public void createAt(){
    	createAt = new Date();
    }
	
	
	@Transient
	private MultipartFile file;
	 
    @Column(name="uiid")
	private String code;	
	
	public Representante(Integer user_id, String nombre, String rfc, String curp, String doctoPdf,
			Date createAt) {
		super();
		this.user_id = user_id;
		this.nombre = nombre;
	 	this.rfc = rfc;
		this.curp = curp;
		this.doctoPdf = doctoPdf;
		this.createAt = createAt;
	}




	public Representante() {
		
		this.code = "RPT" + UUID.randomUUID().toString().substring(26).toUpperCase();
	}
	
	
	
	public Integer getId() {
		return id;
	}



	public void setId(Integer id) {
		this.id = id;
	}



	public Integer getUser_id() {
		return user_id;
	}



	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}



	public String getNombre() {
		return nombre;
	}



	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
 


	public String getRfc() {
		return rfc;
	}



	public void setRfc(String rfc) {
		this.rfc = rfc;
	}



	public String getCurp() {
		return curp;
	}



	public void setCurp(String curp) {
		this.curp = curp;
	}



	public String getDoctoPdf() {
		return doctoPdf;
	}



	public void setDoctoPdf(String doctoPdf) {
		this.doctoPdf = doctoPdf;
	}



	public Date getCreateAt() {
		return createAt;
	}



	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}



	public MultipartFile getFile() {
		return file;
	}




	public void setFile(MultipartFile file) {
		this.file = file;
	}

   
	 
	 
	 
	
	
	public String getCode() {
		return code;
	}




	public void setCode(String code) {
		this.code = code;
	}


	private static final long serialVersionUID = 1L;

	// toString for debugging
		@Override
		public String toString() {
			return "Representante [id=" + id + ",nombre=" + nombre + ", rfc="
					+ rfc + ", curp=" + curp + "]";
		}
	
}
